### ISSUE TITLE
How close we are for working compiler

### ISSUE THREAD

**Issue by emard** [SymbiFlow/prjtrellis#18]
HI

Is there some estimate how close in time we are from working
ECP5 open source compiler similar as ICE40 - months, years?

In the meantime I'd like to share my/our open source PCB design
for Lattice ECP5, it is not yet mass produced (looking for any
manufacturer who would make fully assembled 85F boards for 100$ :)
Board is designed to accept ECP5 chips 12F,  25F,  45F and 85F

https://github.com/emard/ulx3s

**Comment by emard** [comment]
This is really great news! When early tool is ready for simple blink-led example
I'll be happy to test it in on my board!

**Comment by daveshah1** [comment]
That's an awesome board, it would be great the get the open source flow running on it! I'll let you know once something is ready to test. At the moment the first target will be the 45k but it will only be a few days work (just figuring out global clock networks) to add the 25k and the 85k too.

**Comment by emard** [comment]
Thanks!

Let me know if you like to experiment with the board
I'd like to send you one ULX3S board for free as small token
of appreciation for your effort!

Currently I only have left few unfinished prototypes of v1.7 boards
with 45F chip. If I take 2 easy days of funny free time,  I can
manually finish and board will be good to use.

Davor

**Comment by daveshah1** [comment]
I would love to play with a ULX3S board! Will be a great platform for demos. Don't worry if you don't have any 45k, I won't might not support global networks at first anyway so any of the devices will work.
