### ISSUE TITLE
compilation never ends

### ISSUE THREAD

**Issue by emard** [SymbiFlow/prjtrellis#24]
I'm not sure is this right place to post but I installed
fresh prjtrellis-nextpnr-yosys and successfully compiled 
blinky.v compiles fast and works out of the box.

Then I changed simply this
localparam ctr_width = 24
into
localparam ctr_width = 22;

and compilation takes really too long compared to original blinky.v
but actually after few minutes it does it and bitstream works

Info:   processed 1100 jobs. (1100 routed, 0 failed)
Info:   processed 1200 jobs. (1200 routed, 0 failed)

**Comment by daveshah1** [comment]
Seems to be a problem with the A* heuristics provided to the router, possibly after my recent work on timing. I will try and look at this tomorrow. Thanks for reporting!

**Comment by emard** [comment]
fixed
