### ISSUE TITLE
nextpnr fails to route ccu2 cells

### ISSUE THREAD

**Issue by ironsteel** [SymbiFlow/prjtrellis#35]
I don't know if this is related to nextpnr or prjtrellis repo but I'm posting the issue here. 
Please feel free to close this issue if it's not related to prjtrellis and I will reopen it in nextpnr repo.

Trying to compile the bitstream for  the `prjtrellis/examples/versa5g` example I get this error from nextpnr.
```
terminate called after throwing an instance of 'nextpnr_ecp5::assertion_failure'
    what():  Assertion failure: port_fanin.empty() (nextpnr/common/timing.cc:170)     
make: *** [Makefile:12: demo_out.config] Aborted (core dumped)
```

[Here](https://gist.github.com/ironsteel/3d6ce61e394d60a957f25c42c9b5ed6c) is the complete yosys + nextpnr log.

It seems that it fails routing or placing CCU2 cells.

yosys revision is: `23b69ca32b2ef93fc4b3f724099bfecdee0af869`
prjtrellis revision is: `ed7f48f0b02eb656e63c62f9519e5249aa58e4c5`
nextpnr revision is: `b53a4862db99e41f16c06425f314a1a398a21985`

I'm using the prebuild trellis database which is at revision: `32ac96f8573bf14cd9db777e6f046a8530c4411a`

Working around this by adding the `--noccu2` flag to yosys the design is successfully compiled.

**Comment by daveshah1** [comment]
Thanks for the report! Fixed in nextpnr b5faa7ad
