### ISSUE TITLE
Missing support for LFE5-12F devices

### ISSUE THREAD

**Issue by rjordans** [SymbiFlow/prjtrellis#55]
Hi all,
I was looking forward to try out this project on my FPGA board but I noticed that the LFE5-12F chips are not mentioned yet in the database or tools.

What would need to be done to get it added?  If needed I have hardware and the Diamond tools installed so I may be able to help out but I would need to get some instructions on how to get started on this.  I'm a bit short on time though so it may take a while if it requires active effort from my side.

Cheers,
 Roel

**Comment by daveshah1** [comment]
Hi Roel,

There isn't really any 12F silicon. To build a bitstream for the 12F parts, use nextpnr as if you were building for the 25F, then add ` --idcode 0x21111043` to the `ecppack` command line when creating the bitstream itself.

David

**Comment by rjordans** [comment]
Ah, interesting...  Thanks for the info, I´ll go ahead and try the tools on my hardware then!

**Comment by rjordans** [comment]
To avoid confusion.  Would it be an idea to add the 12F parts as alias to the 25F in the tools?

**Comment by C-Elegans** [comment]
Since the 25f and 12f chips share a die, does that mean that you can use all 25k luts on a 12f chip like the iCE40 hx8k and hx4k?

**Comment by daveshah1** [comment]
Yes, you can, however I'd rather not have this a highly advertised "feature" of the Trellis flow at this point in time.
