### ISSUE TITLE
Documentation License

### ISSUE THREAD

**Issue by SadAlpaca** [SymbiFlow/prjtrellis#66]
This git repo for documenting the  Lattice ECP5 bit-stream format says in two places (in readme and contributing) that "all code in the Project Trelli repository is licensed under the very permissive ISC Licence." (emphasis added.) The license itself also says permission is being granted for the software (emphasis also added.) Does that not include the documentation of the  Lattice ECP5 bit-stream format that's being made? Why only the software and not everything?

**Comment by daveshah1** [comment]
The database with the documentation is in its own repo. As stated by its [copying FILE](https://github.com/SymbiFlow/prjtrellis-db/blob/master/COPYING), to the maximum extent that it it is copyrightable, it is licensed under CC0 - public domain for almost all intents and purposes.
